---
name: ci
on:
  - push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: go test -v  ./... -covermode=atomic -coverprofile=coverage.out
      - uses: codecov/codecov-action@v3
        with:
          files: coverage.out
  build:
    name: Build
    permissions:
      packages: write
    runs-on: ubuntu-latest    
    needs: 
      - lint
      - test
    steps:
     - uses: actions/checkout@v3
     - uses: docker/setup-buildx-action@v2
     - uses: docker/setup-qemu-action@v2
     - uses: docker/login-action@v2
       with:
         registery: ghcr.io
         username: ${{github.repository_owner}}
         password: ${{secrets.GITHUB_TOCKEN}}
    - uses: docker/bake-action@v3
      with:
        files: "build/package/docker-bake.json"
        push: true
        
      
     



